---
grails:
    jesque:
        enabled: true
        failedItemLimit: 1000
        pruneWorkersOnStartup: true
        createWorkersOnStartup: true
        schedulerThreadActive: true
        startPaused: false
        nextQueueStrategy: DRAIN_WHILE_MESSAGES_EXISTS

environments:
    test:
        grails:
            jesque:
                pruneWorkersOnStartup: false
                schedulerThreadActive: false

---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: grails.jesque

